---
roles:
- name: geerlingguy.java
- name: geerlingguy.nginx
- name: geerlingguy.pip
- name: geerlingguy.elasticsearch
  version: 1.0.0
- name: geerlingguy.elasticsearch-curator
  version: 2.1.0
- name: geerlingguy.kibana
  version: 1.0.2
- name: geerlingguy.logstash
  version: 5.2.0
- name: geerlingguy.filebeat
  version: 3.2.0
