name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: auto-dependabot-pull-request-merge
      uses: KeisukeYamashita/auto-dependabot-pull-request-merge@v1
